# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 4.0.1.1
    hooks:
      - id: buildifier
        args: &args
          # Keep this argument in sync with .bazelci/config.yaml
          - --warnings=-confusing-name,-constant-glob,-duplicated-name,-function-docstring,-function-docstring-args,-function-docstring-header,-module-docstring,-name-conventions,-no-effect,-constant-glob,-provider-params,-print,-rule-impl-return,-bzl-visibility,-unnamed-macro,-uninitialized,-unreachable
      - id: buildifier-lint
        args: *args
