name: Release Binary Package
on:
  push:
    tags:
      - v*

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: caches-${{ runner.os }}-release
      - name: Build release artifact
        run: mkdir -p bazel-bin/ && touch bazel-bin/rules_kotlin_release.tgz
      - name: Create release sha256
        run: shasum -a 256 bazel-bin/rules_kotlin_release.tgz > bazel-bin/rules_kotlin_release.tgz.sha256
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bazel-bin/rules_kotlin_release.*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: false
          prerelease: true
          release_name: Kotlin rules for Bazel - ${{ github.ref }}
